// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/subscription.proto

package subscriptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BatchGetArticlesRequest is the request for BatchGetPublishedArticles.
type BatchGetArticlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authorizer_appid is the official account appid.
	AuthorizerAppid string `protobuf:"bytes,1,opt,name=authorizer_appid,json=authorizerAppid,proto3" json:"authorizer_appid,omitempty"`
	// offset is the starting position.
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// count is the number of articles to return (1-20).
	Count int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// no_content indicates whether to exclude content field (0 or 1).
	NoContent     int32 `protobuf:"varint,4,opt,name=no_content,json=noContent,proto3" json:"no_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetArticlesRequest) Reset() {
	*x = BatchGetArticlesRequest{}
	mi := &file_api_proto_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetArticlesRequest) ProtoMessage() {}

func (x *BatchGetArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetArticlesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetArticlesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *BatchGetArticlesRequest) GetAuthorizerAppid() string {
	if x != nil {
		return x.AuthorizerAppid
	}
	return ""
}

func (x *BatchGetArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BatchGetArticlesRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BatchGetArticlesRequest) GetNoContent() int32 {
	if x != nil {
		return x.NoContent
	}
	return 0
}

// BatchGetArticlesResponse is the response for BatchGetPublishedArticles.
type BatchGetArticlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total_count is the total number of published articles.
	TotalCount int32 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// item_count is the number of articles in this response.
	ItemCount int32 `protobuf:"varint,2,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	// item is the list of published articles.
	Item          []*PublishedArticle `protobuf:"bytes,3,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetArticlesResponse) Reset() {
	*x = BatchGetArticlesResponse{}
	mi := &file_api_proto_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetArticlesResponse) ProtoMessage() {}

func (x *BatchGetArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetArticlesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetArticlesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *BatchGetArticlesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *BatchGetArticlesResponse) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *BatchGetArticlesResponse) GetItem() []*PublishedArticle {
	if x != nil {
		return x.Item
	}
	return nil
}

// PublishedArticle represents a published article.
type PublishedArticle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// article_id is the unique identifier of the article.
	ArticleId string `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// content is the article content.
	Content *ArticleContent `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// update_time is the last update timestamp.
	UpdateTime    int64 `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedArticle) Reset() {
	*x = PublishedArticle{}
	mi := &file_api_proto_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedArticle) ProtoMessage() {}

func (x *PublishedArticle) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedArticle.ProtoReflect.Descriptor instead.
func (*PublishedArticle) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *PublishedArticle) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *PublishedArticle) GetContent() *ArticleContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PublishedArticle) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// ArticleContent represents the content of an article.
type ArticleContent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// news_item is the list of news items.
	NewsItem      []*NewsItem `protobuf:"bytes,1,rep,name=news_item,json=newsItem,proto3" json:"news_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleContent) Reset() {
	*x = ArticleContent{}
	mi := &file_api_proto_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleContent) ProtoMessage() {}

func (x *ArticleContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleContent.ProtoReflect.Descriptor instead.
func (*ArticleContent) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleContent) GetNewsItem() []*NewsItem {
	if x != nil {
		return x.NewsItem
	}
	return nil
}

// NewsItem represents a single news item.
type NewsItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// title is the article title.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// author is the article author.
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// digest is the article summary.
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// content is the article HTML content.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// content_source_url is the original article URL.
	ContentSourceUrl string `protobuf:"bytes,5,opt,name=content_source_url,json=contentSourceUrl,proto3" json:"content_source_url,omitempty"`
	// thumb_media_id is the cover image media ID.
	ThumbMediaId string `protobuf:"bytes,6,opt,name=thumb_media_id,json=thumbMediaId,proto3" json:"thumb_media_id,omitempty"`
	// thumb_url is the cover image URL.
	ThumbUrl string `protobuf:"bytes,7,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`
	// need_open_comment indicates if comments are enabled.
	NeedOpenComment int32 `protobuf:"varint,8,opt,name=need_open_comment,json=needOpenComment,proto3" json:"need_open_comment,omitempty"`
	// only_fans_can_comment indicates if only fans can comment.
	OnlyFansCanComment int32 `protobuf:"varint,9,opt,name=only_fans_can_comment,json=onlyFansCanComment,proto3" json:"only_fans_can_comment,omitempty"`
	// url is the article URL.
	Url string `protobuf:"bytes,10,opt,name=url,proto3" json:"url,omitempty"`
	// is_deleted indicates if the article is deleted.
	IsDeleted     bool `protobuf:"varint,11,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	mi := &file_api_proto_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *NewsItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsItem) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *NewsItem) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *NewsItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewsItem) GetContentSourceUrl() string {
	if x != nil {
		return x.ContentSourceUrl
	}
	return ""
}

func (x *NewsItem) GetThumbMediaId() string {
	if x != nil {
		return x.ThumbMediaId
	}
	return ""
}

func (x *NewsItem) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *NewsItem) GetNeedOpenComment() int32 {
	if x != nil {
		return x.NeedOpenComment
	}
	return 0
}

func (x *NewsItem) GetOnlyFansCanComment() int32 {
	if x != nil {
		return x.OnlyFansCanComment
	}
	return 0
}

func (x *NewsItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewsItem) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

// GetArticleRequest is the request for GetPublishedArticle.
type GetArticleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authorizer_appid is the official account appid.
	AuthorizerAppid string `protobuf:"bytes,1,opt,name=authorizer_appid,json=authorizerAppid,proto3" json:"authorizer_appid,omitempty"`
	// article_id is the article ID to retrieve.
	ArticleId     string `protobuf:"bytes,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_api_proto_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetArticleRequest) GetAuthorizerAppid() string {
	if x != nil {
		return x.AuthorizerAppid
	}
	return ""
}

func (x *GetArticleRequest) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

// GetArticleResponse is the response for GetPublishedArticle.
type GetArticleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// news_item is the list of news items in the article.
	NewsItem      []*NewsItem `protobuf:"bytes,1,rep,name=news_item,json=newsItem,proto3" json:"news_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_api_proto_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *GetArticleResponse) GetNewsItem() []*NewsItem {
	if x != nil {
		return x.NewsItem
	}
	return nil
}

var File_api_proto_subscription_proto protoreflect.FileDescriptor

const file_api_proto_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/subscription.proto\x12\x12pb.subscription.v1\"\x91\x01\n" +
	"\x17BatchGetArticlesRequest\x12)\n" +
	"\x10authorizer_appid\x18\x01 \x01(\tR\x0fauthorizerAppid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"no_content\x18\x04 \x01(\x05R\tnoContent\"\x94\x01\n" +
	"\x18BatchGetArticlesResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x1d\n" +
	"\n" +
	"item_count\x18\x02 \x01(\x05R\titemCount\x128\n" +
	"\x04item\x18\x03 \x03(\v2$.pb.subscription.v1.PublishedArticleR\x04item\"\x90\x01\n" +
	"\x10PublishedArticle\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12<\n" +
	"\acontent\x18\x02 \x01(\v2\".pb.subscription.v1.ArticleContentR\acontent\x12\x1f\n" +
	"\vupdate_time\x18\x03 \x01(\x03R\n" +
	"updateTime\"K\n" +
	"\x0eArticleContent\x129\n" +
	"\tnews_item\x18\x01 \x03(\v2\x1c.pb.subscription.v1.NewsItemR\bnewsItem\"\xeb\x02\n" +
	"\bNewsItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12,\n" +
	"\x12content_source_url\x18\x05 \x01(\tR\x10contentSourceUrl\x12$\n" +
	"\x0ethumb_media_id\x18\x06 \x01(\tR\fthumbMediaId\x12\x1b\n" +
	"\tthumb_url\x18\a \x01(\tR\bthumbUrl\x12*\n" +
	"\x11need_open_comment\x18\b \x01(\x05R\x0fneedOpenComment\x121\n" +
	"\x15only_fans_can_comment\x18\t \x01(\x05R\x12onlyFansCanComment\x12\x10\n" +
	"\x03url\x18\n" +
	" \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\v \x01(\bR\tisDeleted\"]\n" +
	"\x11GetArticleRequest\x12)\n" +
	"\x10authorizer_appid\x18\x01 \x01(\tR\x0fauthorizerAppid\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\tR\tarticleId\"O\n" +
	"\x12GetArticleResponse\x129\n" +
	"\tnews_item\x18\x01 \x03(\v2\x1c.pb.subscription.v1.NewsItemR\bnewsItem2\xf3\x01\n" +
	"\x13SubscriptionService\x12v\n" +
	"\x19BatchGetPublishedArticles\x12+.pb.subscription.v1.BatchGetArticlesRequest\x1a,.pb.subscription.v1.BatchGetArticlesResponse\x12d\n" +
	"\x13GetPublishedArticle\x12%.pb.subscription.v1.GetArticleRequest\x1a&.pb.subscription.v1.GetArticleResponseBHZFgit.uhomes.net/uhs-go/wechat-subscription-svc/api/proto;subscriptionv1b\x06proto3"

var (
	file_api_proto_subscription_proto_rawDescOnce sync.Once
	file_api_proto_subscription_proto_rawDescData []byte
)

func file_api_proto_subscription_proto_rawDescGZIP() []byte {
	file_api_proto_subscription_proto_rawDescOnce.Do(func() {
		file_api_proto_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_subscription_proto_rawDesc), len(file_api_proto_subscription_proto_rawDesc)))
	})
	return file_api_proto_subscription_proto_rawDescData
}

var file_api_proto_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_subscription_proto_goTypes = []any{
	(*BatchGetArticlesRequest)(nil),  // 0: pb.subscription.v1.BatchGetArticlesRequest
	(*BatchGetArticlesResponse)(nil), // 1: pb.subscription.v1.BatchGetArticlesResponse
	(*PublishedArticle)(nil),         // 2: pb.subscription.v1.PublishedArticle
	(*ArticleContent)(nil),           // 3: pb.subscription.v1.ArticleContent
	(*NewsItem)(nil),                 // 4: pb.subscription.v1.NewsItem
	(*GetArticleRequest)(nil),        // 5: pb.subscription.v1.GetArticleRequest
	(*GetArticleResponse)(nil),       // 6: pb.subscription.v1.GetArticleResponse
}
var file_api_proto_subscription_proto_depIdxs = []int32{
	2, // 0: pb.subscription.v1.BatchGetArticlesResponse.item:type_name -> pb.subscription.v1.PublishedArticle
	3, // 1: pb.subscription.v1.PublishedArticle.content:type_name -> pb.subscription.v1.ArticleContent
	4, // 2: pb.subscription.v1.ArticleContent.news_item:type_name -> pb.subscription.v1.NewsItem
	4, // 3: pb.subscription.v1.GetArticleResponse.news_item:type_name -> pb.subscription.v1.NewsItem
	0, // 4: pb.subscription.v1.SubscriptionService.BatchGetPublishedArticles:input_type -> pb.subscription.v1.BatchGetArticlesRequest
	5, // 5: pb.subscription.v1.SubscriptionService.GetPublishedArticle:input_type -> pb.subscription.v1.GetArticleRequest
	1, // 6: pb.subscription.v1.SubscriptionService.BatchGetPublishedArticles:output_type -> pb.subscription.v1.BatchGetArticlesResponse
	6, // 7: pb.subscription.v1.SubscriptionService.GetPublishedArticle:output_type -> pb.subscription.v1.GetArticleResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_subscription_proto_init() }
func file_api_proto_subscription_proto_init() {
	if File_api_proto_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_subscription_proto_rawDesc), len(file_api_proto_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_subscription_proto_goTypes,
		DependencyIndexes: file_api_proto_subscription_proto_depIdxs,
		MessageInfos:      file_api_proto_subscription_proto_msgTypes,
	}.Build()
	File_api_proto_subscription_proto = out.File
	file_api_proto_subscription_proto_goTypes = nil
	file_api_proto_subscription_proto_depIdxs = nil
}
